### ISSUE TITLE
Trigger ~/Library/Preferences/com.apple.SystemProfiler.plist

### ISSUE THREAD

**Issue by marshki** [marshki/bout_dis_mac#2]
`~/Library/Preferences/com.apple.SystemProfiler.plist` isn't accessible until the GUI "About this Mac" is utilized. Need to trigger this action from a terminal, if possible.

**Comment by marshki** [comment]
Not sure how to trigger this, but added [this](https://github.com/marshki/about_dis_mac/blob/master/functions/hardware_model_too.sh) as a workaround.

**Comment by Thanksagainforlunch** [comment]
Thanks for the shoutout and for cleaning up my quick and dirty example.
